package constants

const GOOGLE_APPLICATION_CREDENTIALS = "GOOGLE_APPLICATION_CREDENTIALS"
const FIREBASE_AUTH_EMULATOR_HOST = "FIREBASE_AUTH_EMULATOR_HOST"

const IMAGE_DB_NAME = "blog"
const GIN_MODE = "GIN_MODE"

const MONGO_DB_URL = "MONGO_DB_URL"
const MONGO_DB_USERNAME = "MONGO_DB_USERNAME"
const MONGO_DB_PASSWORD = "MONGO_DB_PASSWORD"

const USER_ADMIN = "admin"
const USER_EDITOR = "editor"
const USER_VIEWER = "viewer"

const FILE_LOGGING = "FILE_LOGGING"
const FILE_LOGGING_PATH = "FILE_LOGGING_PATH"
const DB_LOGGING = "DB_LOGGING"
const CONSOLE_LOGGING = "CONSOLE_LOGGING"
